# Generated by Django 5.0.6 on 2024-07-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myread", "0002_statuspercent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuspercent",
            options={"verbose_name_plural": "Status Percentages"},
        ),
    ]
